services:
  database:
    container_name: vineward_database
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      PGUSER: vineward
      POSTGRES_USER: vineward
      POSTGRES_PASSWORD: vineward
    expose:
      - 5432
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ../
      dockerfile: docker/Dockerfile-backend
    container_name: vineward_backend
    restart: unless-stopped
    environment:
      DATABASE_URL: ${BACKEND_DATABASE_URL}
      JWT_SECRET_KEY: ${BACKEND_JWT_SECRET_KEY}
    ports:
      - 8080:8080
    depends_on:
      database:
        condition: service_healthy
  frontend:
    build:
      args:
        API_BASE_URL: ${FRONTEND_API_BASE_URL}
        NUXT_UI_PRO_LICENSE: ${FRONTEND_NUXT_UI_PRO_LICENSE}
      context: ../vineward/frontend
      dockerfile: ../../docker/Dockerfile-frontend
    container_name: vineward_frontend
    restart: unless-stopped
    ports:
      - 3000:80
    depends_on:
      - backend
volumes:
  db-data: {}
